<a href="https://colab.research.google.com/github/mayureshjadhav632-cpu/Creation-of-workforce-insights-dashboard-for-employee-skill-and-analytics/blob/main/SQL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Step 1: Create Database and Employee Table

In [15]:
# Create the employees table
cursor = conn.cursor()

cursor.execute("""
CREATE TABLE IF NOT EXISTS employees (
    Employee_ID INTEGER PRIMARY KEY,
    Age INTEGER,
    Gender TEXT,
    Department TEXT,
    Job_Role TEXT,
    Education TEXT,
    Experience INTEGER,
    Salary REAL,
    Performance_Score REAL,
    Job_Satisfaction REAL,
    Work_Life_Balance REAL,
    Training_Hours INTEGER,
    Skills TEXT,
    Promotion_History TEXT,
    Years_At_Company INTEGER,
    Attendance REAL,
    Engagement_Score REAL,
    Attrition TEXT,
    Recruitment_Source TEXT
)
""")

conn.commit()

print("Employee table created successfully!")

Employee table created successfully!

SQL Task 2 — Insert & Manage Employee Data

In [ ]:
# Insert employee records
employees_data = [
    (1, 'John', 30, 'Male', 'Engineering', 'Software Engineer', 5, 70000, 4.5, 4.2, 'No'),
    (2, 'Sarah', 28, 'Female', 'HR', 'HR Executive', 3, 55000, 4.0, 3.8, 'No'),
    (3, 'Mike', 35, 'Male', 'Sales', 'Sales Manager', 8, 85000, 4.7, 4.5, 'No'),
    (4, 'Emma', 26, 'Female', 'Marketing', 'Marketing Executive', 2, 50000, 3.5, 3.2, 'Yes'),
    (5, 'David', 40, 'Male', 'Finance', 'Financial Analyst', 10, 90000, 4.2, 4.0, 'No'),
    (6, 'Priya', 32, 'Female', 'Engineering', 'Data Analyst', 6, 75000, 4.6, 4.4, 'No'),
    (7, 'Alex', 29, 'Male', 'Sales', 'Sales Executive', 4, 60000, 3.8, 3.5, 'Yes'),
    (8, 'Neha', 31, 'Female', 'HR', 'Recruiter', 5, 58000, 4.1, 4.0, 'No'),
    (9, 'Robert', 38, 'Male', 'Engineering', 'Project Manager', 12, 100000, 4.8, 4.6, 'No'),
    (10, 'Anita', 27, 'Female', 'Marketing', 'Content Specialist', 3, 52000, 3.9, 3.7, 'Yes')
]

cursor.executemany("""
INSERT INTO employees
(Employee_ID, Name, Age, Gender, Department, Job_Role,
 Experience, Salary, Performance_Score, Engagement_Score, Attrition)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
""", employees_data)

conn.commit()

print("Employee records inserted successfully!")

Employee records inserted successfully!

In [ ]:
import sqlite3

# Create database
conn = sqlite3.connect('workforce.db')
cursor = conn.cursor()

# Create Employee table
cursor.execute("""
CREATE TABLE IF NOT EXISTS employees (
    Employee_ID INTEGER PRIMARY KEY,
    Name TEXT,
    Age INTEGER,
    Gender TEXT,
    Department TEXT,
    Job_Role TEXT,
    Experience INTEGER,
    Salary REAL,
    Performance_Score REAL,
    Engagement_Score REAL,
    Attrition TEXT
)
""")

conn.commit()
print("Database and Employee table created successfully!")

Database and Employee table created successfully!

In [ ]:
df = pd.read_sql_query("SELECT * FROM employees", conn)
df

,Employee_ID,Name,Age,Gender,Department,Job_Role,Experience,Salary,Performance_Score,Engagement_Score,Attrition
0,1,John,30,Male,Engineering,Software Engineer,5,70000.0,4.5,4.2,No
1,2,Sarah,28,Female,HR,HR Executive,3,55000.0,4.0,3.8,No
2,3,Mike,35,Male,Sales,Sales Manager,8,85000.0,4.7,4.5,No
3,4,Emma,26,Female,Marketing,Marketing Executive,2,50000.0,3.5,3.2,Yes
4,5,David,40,Male,Finance,Financial Analyst,10,90000.0,4.2,4.0,No
5,6,Priya,32,Female,Engineering,Data Analyst,6,75000.0,4.6,4.4,No
6,7,Alex,29,Male,Sales,Sales Executive,4,60000.0,3.8,3.5,Yes
7,8,Neha,31,Female,HR,Recruiter,5,58000.0,4.1,4.0,No
8,9,Robert,38,Male,Engineering,Project Manager,12,100000.0,4.8,4.6,No
9,10,Anita,27,Female,Marketing,Content Specialist,3,52000.0,3.9,3.7,Yes

SQL Task 3 — Data Cleaning & Validation

In [ ]:
cursor.execute("""
SELECT
    COUNT(*) AS Total_Employees,
    SUM(CASE WHEN Name IS NULL THEN 1 ELSE 0 END) AS Missing_Name,
    SUM(CASE WHEN Department IS NULL THEN 1 ELSE 0 END) AS Missing_Department,
    SUM(CASE WHEN Salary IS NULL THEN 1 ELSE 0 END) AS Missing_Salary,
    SUM(CASE WHEN Experience IS NULL THEN 1 ELSE 0 END) AS Missing_Experience
FROM employees
""")

result = cursor.fetchone()

print("Data Validation Result:")
print(result)

Data Validation Result:
(10, 0, 0, 0, 0)

In [ ]:
invalid_data = pd.read_sql_query("""
SELECT *
FROM employees
WHERE Age < 18
   OR Salary < 0
   OR Experience < 0
""", conn)

print("Invalid Records:")
display(invalid_data)

Invalid Records:

Empty DataFrame
Columns: [Employee_ID, Name, Age, Gender, Department, Job_Role, Experience, Salary, Performance_Score, Engagement_Score, Attrition]
Index: []

SQL Task 4 — Demographic Insights using SELECT, WHERE & ORDER BY

In [ ]:
pd.read_sql_query("""
SELECT *
FROM employees
""", conn)

,Employee_ID,Name,Age,Gender,Department,Job_Role,Experience,Salary,Performance_Score,Engagement_Score,Attrition
0,1,John,30,Male,Engineering,Software Engineer,5,70000.0,4.5,4.2,No
1,2,Sarah,28,Female,HR,HR Executive,3,55000.0,4.0,3.8,No
2,3,Mike,35,Male,Sales,Sales Manager,8,85000.0,4.7,4.5,No
3,4,Emma,26,Female,Marketing,Marketing Executive,2,50000.0,3.5,3.2,Yes
4,5,David,40,Male,Finance,Financial Analyst,10,90000.0,4.2,4.0,No
5,6,Priya,32,Female,Engineering,Data Analyst,6,75000.0,4.6,4.4,No
6,7,Alex,29,Male,Sales,Sales Executive,4,60000.0,3.8,3.5,Yes
7,8,Neha,31,Female,HR,Recruiter,5,58000.0,4.1,4.0,No
8,9,Robert,38,Male,Engineering,Project Manager,12,100000.0,4.8,4.6,No
9,10,Anita,27,Female,Marketing,Content Specialist,3,52000.0,3.9,3.7,Yes

SQL Task 5 — Department-wise Employee Distribution

In [ ]:
pd.read_sql_query("""
SELECT
    Department,
    COUNT(*) AS Employee_Count
FROM employees
GROUP BY Department
ORDER BY Employee_Count DESC
""", conn)

    Department  Employee_Count
0  Engineering               3
1        Sales               2
2    Marketing               2
3           HR               2
4      Finance               1

SQL Task 6 — Workforce KPI Calculation
Overall KPIs

In [ ]:
pd.read_sql_query("""
SELECT
    COUNT(*) AS Total_Employees,
    ROUND(AVG(Salary), 2) AS Average_Salary,
    ROUND(AVG(Performance_Score), 2) AS Average_Performance,
    ROUND(AVG(Engagement_Score), 2) AS Average_Engagement,
    ROUND(AVG(Experience), 2) AS Average_Experience
FROM employees
""", conn)

,Total_Employees,Average_Salary,Average_Performance,Average_Engagement,Average_Experience
0,10,69500.0,4.21,3.99,5.8

SQL Task 7 — Identify High & Low Performers

In [ ]:
pd.read_sql_query("""
SELECT
    Employee_ID,
    Name,
    Department,
    Performance_Score
FROM employees
WHERE Performance_Score >= 4.5
ORDER BY Performance_Score DESC
""", conn)

   Employee_ID    Name   Department  Performance_Score
0            9  Robert  Engineering                4.8
1            3    Mike        Sales                4.7
2            6   Priya  Engineering                4.6
3            1    John  Engineering                4.5

SQL Task 8 — Attrition Analysis

In [ ]:
pd.read_sql_query("""
SELECT
    Attrition,
    COUNT(*) AS Employee_Count
FROM employees
GROUP BY Attrition
""", conn)

  Attrition  Employee_Count
0        No               7
1       Yes               3

SQL Task 9 — Department-wise Attrition & Retention

In [ ]:
pd.read_sql_query("""
SELECT
    Department,
    COUNT(*) AS Total_Employees,
    SUM(CASE WHEN Attrition = 'Yes' THEN 1 ELSE 0 END) AS Attrition_Count,
    SUM(CASE WHEN Attrition = 'No' THEN 1 ELSE 0 END) AS Retained_Count,
    ROUND(
        100.0 * SUM(CASE WHEN Attrition = 'Yes' THEN 1 ELSE 0 END)
        / COUNT(*),
        2
    ) AS Attrition_Rate
FROM employees
GROUP BY Department
ORDER BY Attrition_Rate DESC
""", conn)

,Department,Total_Employees,Attrition_Count,Retained_Count,Attrition_Rate
0,Marketing,2,2,0,100.0
1,Sales,2,1,1,50.0
2,HR,2,0,2,0.0
3,Finance,1,0,1,0.0
4,Engineering,3,0,3,0.0

SQL Task 10 — Employee Performance Analysis

In [18]:
pd.read_sql_query("""
SELECT
    Department,
    AVG(Performance_Score) AS Average_Performance
FROM employees
GROUP BY Department
ORDER BY Average_Performance DESC;
""", conn)

Empty DataFrame
Columns: [Department, Average_Performance]
Index: []

In [19]:
pd.read_sql_query("""
SELECT
    Department,
    COUNT(*) AS Total_Employees,
    ROUND(AVG(Performance_Score), 2) AS Average_Performance,
    MAX(Performance_Score) AS Highest_Performance,
    MIN(Performance_Score) AS Lowest_Performance
FROM employees
GROUP BY Department
ORDER BY Average_Performance DESC;
""", conn)

Empty DataFrame
Columns: [Department, Total_Employees, Average_Performance, Highest_Performance, Lowest_Performance]
Index: []